2024 Update
Cyfrin/foundry-full-course-cu pull request #2055
Opened 2024-07-18 18:11 UTC by cromewar

- Added all the links to point to updraft for all sections.
- Changed the video thumbnails and links to point to youtube.
- Added new sections for the update. (wallet attraction and more).

2024-07-19 19:16 UTC, PatrickAlphaC requested changes
I don't understand the markdown hierarchy. Why is does `foundry fundamentals` have 2 `#`s, but a lot of the sections "inside" the course also have 2 `#`s?

```
## Foundry fundamentals
```

Can we have a standard?

Course layout:
```
# <course name>
## <course name> | <section name>
### <lesson>
#### <additional stuff>
```

can we also not have it say `course NFT`, it doesn't make sense. it's the `section` nft.

Remember, the hierarchy is:

```
course -> section -> lesson
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +<a href="https://youtu.be/WIsXSwo4iDc?si=PkLPgHmsmlHE07wF" target="_blank">
```suggestion
<a href="https://updraft.cyfrin.io/courses/blockchain-basics" target="_blank">
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +        <img src="./thumbnails/2024-update.png" width="750" alt="Blockchain Developer, Smart Contract, & Solidity Course - Powered By AI 1">
```suggestion
        <img src="./thumbnails/2024-update.png" width="750" alt="Blockchain Developer, Smart Contract, & Solidity Course - Powered By AI">
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +[YouTube Link](https://youtu.be/WIsXSwo4iDc?si=PkLPgHmsmlHE07wF)
```suggestion
[YouTube Link](https://www.youtube.com/watch?v=-1GB6m39-rM)
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +
```suggestion
## Solidity 101 Section 1: Simple Storage
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +## The EVM & A Recap of the course
```suggestion
## The EVM & A Recap of the section
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +## Course Section 1 NFTs
```suggestion
## Simple Storage NFTs
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +# Course Section 2 | Remix Storage Factory
```suggestion
# Solidity 101 Section 2 | Remix Storage Factory
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +# Course: Solidity & Smart Contract Developmnet
```suggestion
# Course: Solidity 101
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +## Course Section 2 NFTs
```suggestion
## Section 2 NFTs
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +# Section 3: Remix Fund Me
```suggestion
# Solidity 101 Section 3: Remix Fund Me
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +## Course Section 3 NFTs
```suggestion
## Section 3 NFTs
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +_[⭐️ Section 4 | AI Prompting](https://updraft.cyfrin.io/courses/solidity/ai-prompting/ai-and-forums)_
```suggestion
# Solidity 101 Section 4: AI Prompting

_[⭐️ Section 4 | AI Prompting](https://updraft.cyfrin.io/courses/solidity/ai-prompting/ai-and-forums)_
```

2024-07-19 19:16 UTC, PatrickAlphaC commented on README.md
> +## Course Section 4 NFTs
```suggestion
## Section 4 NFTs
```

2024-08-01 01:03 UTC, merged

2024-09-14 12:56 UTC, jefrenchee commented on README.md
> +## Course Section 1 NFTs
tank you